#!/bin/bash

# Function to view all iptables firewall rules with color formatting
function viewfirewall() {
    echo -e "Viewing all iptables firewall rules...\n"

    echo -e "\033[1;36mIncoming Rules:\033[0m"
    sudo iptables -L INPUT -v -n --line-numbers

    echo -e "\n\033[1;36mForward Rules:\033[0m"
    sudo iptables -L FORWARD -v -n --line-numbers

    echo -e "\n\033[1;36mOutgoing Rules:\033[0m"
    sudo iptables -L OUTPUT -v -n --line-numbers

    echo -e "\n\033[1;36mNAT Rules:\033[0m"
    sudo iptables -t nat -L -v -n --line-numbers

    echo -e "\n\033[1;36mMangle Rules:\033[0m"
    sudo iptables -t mangle -L -v -n --line-numbers

    echo -e "\n\033[1;36mRaw Rules:\033[0m"
    sudo iptables -t raw -L -v -n --line-numbers
}
