#!/bin/bash

function helpcmd() {
    case $1 in
        filesearch)
            echo -e "filesearch: Search for files by name."
            echo -e "Syntax: filesearch <filename-pattern>"
            echo -e "Example: filesearch '*.txt'"
            ;;
        bigfiles)
            echo -e "bigfiles: List largest files in the current directory."
            echo -e "Syntax: bigfiles"
            echo -e "Example: bigfiles"
            ;;
        showhidden)
            echo -e "showhidden: Show hidden files and directories."
            echo -e "Syntax: showhidden"
            echo -e "Example: showhidden"
            ;;
        editfile)
            echo -e "editfile: Open a file for editing."
            echo -e "Syntax: editfile <filename>"
            echo -e "Example: editfile example.txt"
            ;;
        extract)
            echo -e "extract: Extract a tar.gz archive."
            echo -e "Syntax: extract <archive.tar.gz>"
            echo -e "Example: extract archive.tar.gz"
            ;;
        compress)
            echo -e "compress: Create a tar.gz archive."
            echo -e "Syntax: compress <output.tar.gz> <files/directories>"
            echo -e "Example: compress backup.tar.gz myfolder/"
            ;;
        home|cd..|..|...|....|.....)
            echo -e "$1: Navigate directories."
            echo -e "Syntax: $1 (no additional arguments)"
            echo -e "Example: $1"
            ;;
        bd)
            echo -e "bd: Return to the previous directory."
            echo -e "Syntax: bd"
            echo -e "Example: bd"
            ;;
        rmd)
            echo -e "rmd: Remove a directory and all files."
            echo -e "Syntax: rmd <directory>"
            echo -e "Example: rmd tempfolder/"
            ;;
        viewsyslogs|viewapplogs|viewrebootlogs|viewwarninglogs|viewerrorlogs|viewauthlogs)
            case $1 in
                viewsyslogs) desc="View system logs"; syntax="viewsyslogs"; example="viewsyslogs";;
                viewapplogs) desc="View logs for a specific application"; syntax="viewapplogs <application-name>"; example="viewapplogs apache2";;
                viewrebootlogs) desc="View reboot logs"; syntax="viewrebootlogs"; example="viewrebootlogs";;
                viewwarninglogs) desc="View warning logs"; syntax="viewwarninglogs"; example="viewwarninglogs";;
                viewerrorlogs) desc="View error logs"; syntax="viewerrorlogs"; example="viewerrorlogs";;
                viewauthlogs) desc="View authentication logs"; syntax="viewauthlogs"; example="viewauthlogs";;
            esac
            echo -e "$1: $desc."
            echo -e "Syntax: $syntax"
            echo -e "Example: $example"
            ;;
        lsof-established|lsof-udp|lsof-port|lsof-listen|lsof-network|lsof-ipv4|lsof-ipv6)
            case $1 in
                lsof-established) desc="List established TCP connections"; syntax="lsof-established"; example="lsof-established";;
                lsof-udp) desc="List UDP connections"; syntax="lsof-udp"; example="lsof-udp";;
                lsof-port) desc="List processes using a specific port"; syntax="lsof-port <port-number>"; example="lsof-port 80";;
                lsof-listen) desc="List listening ports"; syntax="lsof-listen"; example="lsof-listen";;
                lsof-network) desc="Show network connections with associated processes"; syntax="lsof-network"; example="lsof-network";;
                lsof-ipv4) desc="Show only IPv4 network connections"; syntax="lsof-ipv4"; example="lsof-ipv4";;
                lsof-ipv6) desc="Show only IPv6 network connections"; syntax="lsof-ipv6"; example="lsof-ipv6";;
            esac
            echo -e "$1: $desc."
            echo -e "Syntax: $syntax"
            echo -e "Example: $example"
            ;;
        install|remove|purge|autoremove|search|showupgrades|updaterepo|fullupdate|showinstalledpkgs|showpkgs|showpackagefiles|showpkgssize)
            case $1 in
                install) desc="Install a package"; syntax="install <package-name>"; example="install vim";;
                remove|purge) desc="Remove a package"; syntax="remove <package-name>"; example="remove vim";;
                autoremove) desc="Remove unused dependencies"; syntax="autoremove"; example="autoremove";;
                search) desc="Search for a package"; syntax="search <package-name>"; example="search vim";;
                showupgrades) desc="Show available upgrades"; syntax="showupgrades"; example="showupgrades";;
                updaterepo) desc="Update package lists"; syntax="updaterepo"; example="updaterepo";;
                fullupdate) desc="Upgrade all packages"; syntax="fullupdate"; example="fullupdate";;
                showinstalledpkgs|showpkgs) desc="List installed packages"; syntax="$1"; example="$1";;
                showpackagefiles) desc="Show files installed by a package"; syntax="showpackagefiles <package-name>"; example="showpackagefiles vim";;
                showpkgssize) desc="Display package sizes"; syntax="showpkgssize"; example="showpkgssize";;
            esac
            echo -e "$1: $desc."
            echo -e "Syntax: $syntax"
            echo -e "Example: $example"
            ;;
        ipinfo|netstatl|cpuinfo|meminfo|diskinfo|editbash|reloadbash|fullreload)
            case $1 in
                ipinfo) desc="Show public IP information"; syntax="ipinfo"; example="ipinfo";;
                netstatl) desc="List all listening ports"; syntax="netstatl"; example="netstatl";;
                cpuinfo) desc="Show CPU information"; syntax="cpuinfo"; example="cpuinfo";;
                meminfo) desc="Show memory usage"; syntax="meminfo"; example="meminfo";;
                diskinfo) desc="Show disk usage"; syntax="diskinfo"; example="diskinfo";;
                editbash) desc="Edit bash configuration"; syntax="editbash"; example="editbash";;
                reloadbash) desc="Reload bash configuration"; syntax="reloadbash"; example="reloadbash";;
                fullreload) desc="Fully reload terminal and services"; syntax="fullreload"; example="fullreload";;
            esac
            echo -e "$1: $desc."
            echo -e "Syntax: $syntax"
            echo -e "Example: $example"
            ;;
        "")
            echo -e "Available Commands (Use 'helpcmd <command>' for details):"
            echo -e "File Management: filesearch, bigfiles, showhidden, editfile"
            echo -e "Archive Management: extract, compress"
            echo -e "Directory Navigation: home, cd.., .., ..., ...., ....."
            echo -e "System Logs: viewsyslogs, viewapplogs, viewrebootlogs, viewwarninglogs, viewerrorlogs, viewauthlogs"
            echo -e "Network Tools: ipinfo, netstatl, lsof-*"
            echo -e "Package Management: install, remove, purge, autoremove, search, showupgrades, updaterepo, fullupdate"
            echo -e "System Info: cpuinfo, meminfo, diskinfo"
            echo -e "Shell Management: editbash, reloadbash, fullreload"
            ;;
        *)
            echo "Error: Unknown command '$1'. Use 'helpcmd' to list available commands."
            ;;
    esac
}
