#!/bin/bash

function helpcmd() {
    local command=$1

    # Format output
    print_help() {
        echo -e "\n=== HELP: $1 ==="
        echo -e "Description: $2"
        echo -e "Syntax: $3"
        echo -e "Example: $4"
        echo
    }

    # Main 
    case $command in
        filesearch)
            print_help "filesearch" \
                "Search for files by name." \
                "filesearch <filename-pattern>" \
                "filesearch '*.txt'"
            ;;
        bigfiles)
            print_help "bigfiles" \
                "List largest files in the current directory." \
                "bigfiles" \
                "bigfiles"
            ;;
        showhidden)
            print_help "showhidden" \
                "Show hidden files and directories." \
                "showhidden" \
                "showhidden"
            ;;
        editfile)
            print_help "editfile" \
                "Open a file for editing." \
                "editfile <filename>" \
                "editfile example.txt"
            ;;
        extract)
            print_help "extract" \
                "Extract a tar.gz archive." \
                "extract <archive.tar.gz>" \
                "extract archive.tar.gz"
            ;;
        compress)
            print_help "compress" \
                "Create a tar.gz archive." \
                "compress <output.tar.gz> <files/directories>" \
                "compress backup.tar.gz myfolder/"
            ;;
        home|cd..|..|...|....|.....)
            print_help "$command" \
                "Navigate directories." \
                "$command" \
                "$command"
            ;;
        bd)
            print_help "bd" \
                "Return to the previous directory." \
                "bd" \
                "bd"
            ;;
        rmd)
            print_help "rmd" \
                "Remove a directory and all files within it." \
                "rmd <directory>" \
                "rmd tempfolder/"
            ;;
        viewsyslogs|viewapplogs|viewrebootlogs|viewwarninglogs|viewerrorlogs|viewauthlogs)
            local desc syntax example
            case $command in
                viewsyslogs) desc="View system logs"; syntax="viewsyslogs"; example="viewsyslogs";;
                viewapplogs) desc="View logs for a specific application"; syntax="viewapplogs <application-name>"; example="viewapplogs apache2";;
                viewrebootlogs) desc="View reboot logs"; syntax="viewrebootlogs"; example="viewrebootlogs";;
                viewwarninglogs) desc="View warning logs"; syntax="viewwarninglogs"; example="viewwarninglogs";;
                viewerrorlogs) desc="View error logs"; syntax="viewerrorlogs"; example="viewerrorlogs";;
                viewauthlogs) desc="View authentication logs"; syntax="viewauthlogs"; example="viewauthlogs";;
            esac
            print_help "$command" "$desc" "$syntax" "$example"
            ;;
        lsof-*)
            local desc syntax example
            case $command in
                lsof-established) desc="List established TCP connections"; syntax="lsof-established"; example="lsof-established";;
                lsof-udp) desc="List UDP connections"; syntax="lsof-udp"; example="lsof-udp";;
                lsof-port) desc="List processes using a specific port"; syntax="lsof-port <port-number>"; example="lsof-port 80";;
                lsof-listen) desc="List listening ports"; syntax="lsof-listen"; example="lsof-listen";;
                lsof-network) desc="Show network connections with associated processes"; syntax="lsof-network"; example="lsof-network";;
                lsof-ipv4) desc="Show only IPv4 network connections"; syntax="lsof-ipv4"; example="lsof-ipv4";;
                lsof-ipv6) desc="Show only IPv6 network connections"; syntax="lsof-ipv6"; example="lsof-ipv6";;
            esac
            print_help "$command" "$desc" "$syntax" "$example"
            ;;
        install|remove|purge|autoremove|search|showupgrades|updaterepo|fullupdate|showinstalledpkgs|showpkgs|showpackagefiles|showpkgssize)
            local desc syntax example
            case $command in
                install) desc="Install a package"; syntax="install <package-name>"; example="install vim";;
                remove|purge) desc="Remove a package"; syntax="remove <package-name>"; example="remove vim";;
                autoremove) desc="Remove unused dependencies"; syntax="autoremove"; example="autoremove";;
                search) desc="Search for a package"; syntax="search <package-name>"; example="search vim";;
                showupgrades) desc="Show available upgrades"; syntax="showupgrades"; example="showupgrades";;
                updaterepo) desc="Update package lists"; syntax="updaterepo"; example="updaterepo";;
                fullupdate) desc="Upgrade all packages"; syntax="fullupdate"; example="fullupdate";;
                showinstalledpkgs|showpkgs) desc="List installed packages"; syntax="$command"; example="$command";;
                showpackagefiles) desc="Show files installed by a package"; syntax="showpackagefiles <package-name>"; example="showpackagefiles vim";;
                showpkgssize) desc="Display package sizes"; syntax="showpkgssize"; example="showpkgssize";;
            esac
            print_help "$command" "$desc" "$syntax" "$example"
            ;;
        ipinfo|netstatl|cpuinfo|meminfo|diskinfo|editbash|reloadbash|fullreload)
            local desc syntax example
            case $command in
                ipinfo) desc="Show public IP information"; syntax="ipinfo"; example="ipinfo";;
                netstatl) desc="List all listening ports"; syntax="netstatl"; example="netstatl";;
                cpuinfo) desc="Show CPU information"; syntax="cpuinfo"; example="cpuinfo";;
                meminfo) desc="Show memory usage"; syntax="meminfo"; example="meminfo";;
                diskinfo) desc="Show disk usage"; syntax="diskinfo"; example="diskinfo";;
                editbash) desc="Edit bash configuration"; syntax="editbash"; example="editbash";;
                reloadbash) desc="Reload bash configuration"; syntax="reloadbash"; example="reloadbash";;
                fullreload) desc="Fully reload terminal and services"; syntax="fullreload"; example="fullreload";;
            esac
            print_help "$command" "$desc" "$syntax" "$example"
            ;;
        "")
            echo -e "\n=== HELP MENU ==="
            echo -e "Use 'helpcmd <command>' to get detailed help on a specific command.\n"
            echo -e "Categories of Commands:"
            echo -e "1. File Management: filesearch, bigfiles, showhidden, editfile"
            echo -e "2. Archive Management: extract, compress"
            echo -e "3. Directory Navigation: home, cd.., .., ..., ...., ....., bd, rmd"
            echo -e "4. Logs: viewsyslogs, viewapplogs, viewrebootlogs, viewwarninglogs, viewerrorlogs, viewauthlogs"
            echo -e "5. Network: ipinfo, netstatl, lsof-*"
            echo -e "6. Package Management: install, remove, search, autoremove, fullupdate, updaterepo, showupgrades"
            echo -e "7. System Info: cpuinfo, meminfo, diskinfo"
            echo -e "8. Shell Tools: editbash, reloadbash, fullreload"
            echo
            ;;
        *)
            echo -e "\nError: Unknown command '$command'. Use 'helpcmd' to list available commands."
            ;;
    esac
}
