#!/bin/bash

# Function to update system packages without installing new packages
function updatebasesystem() {
	echo "Updating system packages without installing new packages..."
	sudo apt update
	sudo apt upgrade --without-new-pkgs --no-install-recommends
}

function fullupgrade() {
	echo "Updating system and user packages together..."
	sudo apt update
	sudo apt full-upgrade
}

# Package management aliases
alias install='sudo apt install'
alias remove='sudo apt remove'
alias purge='remove'
alias autoremove='sudo apt autoremove'
alias search='apt search'
alias showupgrades='apt list --upgradable'  # Show available package upgrades
alias updaterepo='sudo apt update'
alias fullupdate='fullupgrade'  # Upgrade packages, including kernel packages
alias showinstalledpkgs='dpkg -l'  # Show installed packages
alias showpkgs='dpkg -l'  # Show installed packages
alias showpackagefiles='dpkg -L'     # Show files installed by a package
alias showpkgssize='dpkg-query -W --showformat="\${Installed-Size;10}\t\${Package}\n" | sort -n'  # Show installed package sizes


